name: a8_brunas_task_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  sqflite: ^1.3.0+2
  provider: ^4.1.1

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: 'dev_assets/bruna.thumbsUp.png'

flutter:

  uses-material-design: true

  assets:
    - assets/bruna.left.png
    - assets/bruna.left.thumbsUp.png
